return 
{
	["Attribute"] = {
		["BaseAtr"] = {
			["Amount"] = {
				["CnName"] = "数量",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Binds"] = {
				["CnName"] = "使用绑定",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["ExpiryDate"] = {
				["CnName"] = "有效期",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["ItemId"] = {
				["CnName"] = "道具编号",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
		},
		["BuildAtr"] = {
			["AutoUse"] = {
				["CnName"] = "自动使用",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Bind"] = {
				["CnName"] = "绑定",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["BuyPrice"] = {
				["CnName"] = "购买价格",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Category"] = {
				["CnName"] = "大类",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["DefaultScale"] = {
				["CnName"] = "缩放值",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Desc"] = {
				["CnName"] = "描述",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Extraction"] = {
				["CnName"] = "抽取结果",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["IconName"] = {
				["CnName"] = "图标名称",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["MaxUseTimes"] = {
				["CnName"] = "每日使用上限",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["ModelId"] = {
				["CnName"] = "模型ID",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Name"] = {
				["CnName"] = "名称",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["NeedLevel"] = {
				["CnName"] = "需求等级",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Param1"] = {
				["CnName"] = "参数1",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Param2"] = {
				["CnName"] = "参数2",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Price"] = {
				["CnName"] = "价格",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["PriceType"] = {
				["CnName"] = "价钱类型",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Quality"] = {
				["CnName"] = "品质",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["SellPrice"] = {
				["CnName"] = "出售价格",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Sort"] = {
				["CnName"] = "小类",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["SortId"] = {
				["CnName"] = "小类Id",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["SubType"] = {
				["CnName"] = "使用类",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
		},
	},
	["ConstInfo"] = {
		["配置表"] = {
			[45001] = {
				["Binds"] = 1,
				["BuyPrice"] = 1000,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "服用可恢复体力60点",
				["IconName"] = "物品_道具-1",
				["MaxUseTimes"] = 10,
				["ModelId"] = 40007,
				["Name"] = "体力药剂",
				["NeedLevel"] = 1,
				["Param1"] = "Strength",
				["Param2"] = "60",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10,
				["Sort"] = "恢复类药品",
			},
			[45002] = {
				["Binds"] = 1,
				["BuyPrice"] = 100,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "回复生命1000点",
				["IconName"] = "物品_道具-2",
				["ModelId"] = 40007,
				["Name"] = "生命之泉",
				["NeedLevel"] = 1,
				["Param1"] = "Hp",
				["Param2"] = "1000",
				["PriceType"] = {
					1,
				},
				["Quality"] = 3,
				["SellPrice"] = 10,
				["Sort"] = "恢复类药品",
			},
			[45003] = {
				["BuyPrice"] = 100,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "金币",
				["IconName"] = "物品_道具-3",
				["ModelId"] = 40007,
				["Name"] = "金币包",
				["NeedLevel"] = 1,
				["Param1"] = "Money",
				["Param2"] = "100",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 100,
				["Sort"] = "代金物",
			},
			[45004] = {
				["BuyPrice"] = 100,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "大量金币",
				["IconName"] = "物品_道具-4",
				["ModelId"] = 40007,
				["Name"] = "金币大包",
				["NeedLevel"] = 1,
				["Param1"] = "Money",
				["Param2"] = "1000",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 100,
				["Sort"] = "代金物",
			},
			[45005] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "激光镌刻笔，可在基因上镌刻出你想说的一句话。",
				["IconName"] = "小羽翼",
				["ModelId"] = 40007,
				["Name"] = "激光镌刻笔",
				["NeedLevel"] = 1,
				["Quality"] = 4,
				["Sort"] = "商城消耗品",
			},
			[45006] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用星辰之力激活宝箱，唤醒隐藏的稀有道具。免费获取一次装备宝箱的购买机会。",
				["IconName"] = "小羽翼",
				["ModelId"] = 40007,
				["Name"] = "唤灵钥匙",
				["NeedLevel"] = 1,
				["Quality"] = 4,
				["Sort"] = "商城消耗品",
			},
			[45501] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "能卖一点金币。",
				["IconName"] = "物品_道具-1",
				["ModelId"] = 40007,
				["Name"] = "小石块",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 1,
				["SellPrice"] = 500,
				["Sort"] = "代金物",
			},
			[45502] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "能卖一些金币。",
				["IconName"] = "物品_道具-2",
				["ModelId"] = 40007,
				["Name"] = "大石块",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 1000,
				["Sort"] = "代金物",
			},
			[45503] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "微微发光，能卖较多金币。",
				["IconName"] = "物品_道具-3",
				["ModelId"] = 40007,
				["Name"] = "小晶体",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 5000,
				["Sort"] = "代金物",
			},
			[45504] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "闪闪发光，能卖大量金币。",
				["IconName"] = "物品_道具-4",
				["ModelId"] = 40007,
				["Name"] = "大晶体",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "代金物",
			},
			[45505] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "罕见晶钻，能获得人生一桶金。",
				["IconName"] = "极品子弹匣专用",
				["ModelId"] = 40007,
				["Name"] = "晶钻",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 100000,
				["Sort"] = "代金物",
			},
			[48001] = {
				["Bind"] = 1,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活一阶血技",
				["IconName"] = "一阶血技书",
				["ModelId"] = 40007,
				["Name"] = "一阶血技书",
				["NeedLevel"] = 1,
				["Price"] = 50,
				["PriceType"] = {
					0,
				},
				["Quality"] = 1,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48002] = {
				["Bind"] = 1,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技斩月·逆乱",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "斩月·逆乱",
				["NeedLevel"] = 1,
				["Price"] = 5000,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48003] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技胧月·吸虹",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "胧月·吸虹",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48004] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技一闪·血怒",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "一闪·血怒",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48005] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技突刺·无影",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "突刺·无影",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48006] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技拔刀·破空",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "拔刀·破空",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48007] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技剑舞·噬灵",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "剑舞·噬灵",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48008] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技斩空·炎爆",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "斩空·炎爆",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48009] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技弑空·断水",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "弑空·断水",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48010] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "用来激活黑血技翻斩·奔雷",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "翻斩·奔雷",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48011] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "激活黑血技·强化风火轮的必需品",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "强化风火轮",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48012] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活黑血技落雁·火山",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "落雁·火山",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48013] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活黑血技狼牙·旭日",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "狼牙·旭日",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48014] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "激活黑血技·轮舞·尾斩的必需品",
				["IconName"] = "五阶血技书",
				["ModelId"] = 40007,
				["Name"] = "轮舞·尾斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48015] = {
				["Bind"] = 1,
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活二阶血技",
				["IconName"] = "二阶血技书",
				["ModelId"] = 40007,
				["Name"] = "二阶血技书",
				["NeedLevel"] = 1,
				["Price"] = 100,
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48016] = {
				["Bind"] = 1,
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技真·斩月",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "真·斩月",
				["NeedLevel"] = 1,
				["Price"] = 300,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48017] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技强·胧月",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "强·胧月",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48018] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技破·胧月",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "破·胧月",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48019] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技一闪",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "一闪",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48020] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技霸·突刺",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "霸·突刺",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48021] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技蓄力斩",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "蓄力斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48022] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技瞬斩",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "瞬斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48023] = {
				["Bind"] = 1,
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技疾·剑舞",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "疾·剑舞",
				["NeedLevel"] = 1,
				["Price"] = 800,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48024] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技劫·剑舞",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "劫·剑舞",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48025] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技强·升龙",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "强·升龙",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48026] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技追·尾斩",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "追·尾斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48027] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技力·斩空",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "力·斩空",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48028] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技精·弑空",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "精·弑空",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48029] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技疾·剑舞",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "锋·翻斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48030] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技劫·剑舞",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "刃·风车",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48031] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技强·落雁",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "强·落雁",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48032] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活三阶血技强·狼牙",
				["IconName"] = "三阶血技书",
				["ModelId"] = 40007,
				["Name"] = "强·狼牙",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48033] = {
				["Bind"] = 1,
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技破·落雁",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "破·落雁",
				["NeedLevel"] = 1,
				["Price"] = 2000,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48034] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技嗜血·狼牙",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "嗜血·狼牙",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48035] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技追命·斩空",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "追命·斩空",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48036] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技暴·弑空",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "暴·弑空",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48037] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技裂·一闪",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "裂·一闪",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48038] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技疾·突刺",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "疾·突刺",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48039] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技寒·斩月",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "寒·斩月",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48040] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技爆·斩月",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "爆·斩月",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48041] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技极·胧月",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "极·胧月",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48042] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技恒·胧月",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "恒·胧月",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48043] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技雷·翻斩",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "雷·翻斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48044] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技炎·风车",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "炎·风车",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48045] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技狂怒·升龙",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "狂怒·升龙",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48046] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技破军·升龙",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "破军·升龙",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48047] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技飞狐·尾斩",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "飞狐·尾斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48048] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技嗜·剑舞",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "嗜·剑舞",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48049] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技逸风·剑舞",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "逸风·剑舞",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48050] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技群·蓄力斩",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "群·蓄力斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[48051] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技闪·蓄力斩",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "闪·蓄力斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 50000,
				["Sort"] = "血技技能书",
			},
			[48052] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "用来激活四阶血技强·瞬斩",
				["IconName"] = "四阶血技书",
				["ModelId"] = 40007,
				["Name"] = "强·瞬斩",
				["NeedLevel"] = 1,
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 10000,
				["Sort"] = "血技技能书",
			},
			[49001] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得劣质的子弹，低概率获得普通品质的子弹。",
				["IconName"] = "劣质子弹匣",
				["ModelId"] = 40000,
				["Name"] = "劣质子弹匣",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1001",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 2000,
				["Sort"] = "宝箱",
			},
			[49002] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开必定获得适用于自身的劣质子弹，较低概率获得普通品质的子弹。",
				["IconName"] = "劣质子弹匣",
				["ModelId"] = 40000,
				["Name"] = "劣质子弹匣(专)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1002",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 2000,
				["Sort"] = "宝箱",
			},
			[49003] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得劣质的冲锋枪子弹，较低概率获得普通品质的冲锋枪子弹。",
				["IconName"] = "劣质子弹匣",
				["ModelId"] = 40000,
				["Name"] = "劣质子弹匣(冲锋)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1003",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 2000,
				["Sort"] = "宝箱",
			},
			[49004] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得劣质的重炮子弹，较低概率获得普通品质的重炮子弹。",
				["IconName"] = "劣质子弹匣专用",
				["ModelId"] = 40000,
				["Name"] = "劣质子弹匣(重炮)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1004",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 2000,
				["Sort"] = "宝箱",
			},
			[49005] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得普通品质的子弹，较低概率获得稀有品质的子弹。",
				["IconName"] = "普通子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "普通子弹匣",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1005",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "宝箱",
			},
			[49006] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开必定获得适用于自身的普通品质子弹，较低概率获得稀有品质的子弹。",
				["IconName"] = "普通子弹匣专用",
				["ModelId"] = 40000,
				["Name"] = "普通子弹匣(专)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1006",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "宝箱",
			},
			[49007] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得普通品质的冲锋枪子弹，较低概率获得稀有品质的冲锋枪子弹。",
				["IconName"] = "普通子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "普通子弹匣(冲锋枪)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1007",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "宝箱",
			},
			[49008] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得普通品质的重炮子弹，较低概率获得稀有品质的重炮子弹。",
				["IconName"] = "普通子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "普通子弹匣(重炮)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1008",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10000,
				["Sort"] = "宝箱",
			},
			[49009] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得稀有品质的冲锋枪子弹，极低概率获得极品品质的冲锋枪子弹。",
				["IconName"] = "稀有子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "稀有子弹匣",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1009",
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 30000,
				["Sort"] = "宝箱",
			},
			[49010] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开必定获得适用于自身的稀有品质子弹，较低概率获得极品品质的子弹。",
				["IconName"] = "稀有子弹匣专用",
				["ModelId"] = 40000,
				["Name"] = "稀有子弹匣(专)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1010",
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 30000,
				["Sort"] = "宝箱",
			},
			[49011] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得稀有品质的冲锋枪子弹，极低概率获得极品品质的冲锋枪子弹。",
				["IconName"] = "稀有子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "稀有子弹匣(冲锋枪)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1011",
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 30000,
				["Sort"] = "宝箱",
			},
			[49012] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得稀有品质的重炮子弹，极低概率获得极品品质的重炮子弹。",
				["IconName"] = "稀有子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "稀有子弹匣(重炮)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1012",
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 30000,
				["Sort"] = "宝箱",
			},
			[49013] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "极高概率获得极品的子弹，低概率获得两颗稀有子弹，极低概率获得三颗稀有子弹",
				["IconName"] = "极品子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "极品子弹匣",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1013",
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 100000,
				["Sort"] = "宝箱",
			},
			[49014] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开必定获得适用于自身的极品品质子弹，较低概率获得两颗极品。",
				["IconName"] = "极品子弹匣专用",
				["ModelId"] = 40000,
				["Name"] = "极品子弹匣(专)",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1014",
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 100000,
				["Sort"] = "宝箱",
			},
			[49015] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个紫色振幅晶体。",
				["IconName"] = "紫色振幅晶体",
				["ModelId"] = 40000,
				["Name"] = "极品振幅晶体包",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2032",
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49016] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个蓝色振幅晶体。",
				["IconName"] = "蓝色振幅晶体",
				["ModelId"] = 40000,
				["Name"] = "稀有振幅晶体包",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2033",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49017] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个绿品振幅晶体。",
				["IconName"] = "绿色振幅晶体",
				["ModelId"] = 40000,
				["Name"] = "普通振幅晶体包",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2034",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49018] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个橙色振幅晶体。",
				["IconName"] = "橙色振幅晶体",
				["ModelId"] = 40007,
				["Name"] = "振幅晶体（橙）",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2031",
				["PriceType"] = {
					0,
				},
				["Quality"] = 5,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49019] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个紫色振幅晶体。",
				["IconName"] = "紫色振幅晶体",
				["ModelId"] = 40000,
				["Name"] = "振幅晶体（紫）",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2032",
				["PriceType"] = {
					0,
				},
				["Quality"] = 4,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49020] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个蓝色振幅晶体。",
				["IconName"] = "蓝色振幅晶体",
				["ModelId"] = 40000,
				["Name"] = "振幅晶体（蓝）",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2033",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49021] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开随机获得1个绿色振幅晶体。",
				["IconName"] = "绿色振幅晶体",
				["ModelId"] = 40000,
				["Name"] = "振幅晶体（绿）",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "2034",
				["PriceType"] = {
					0,
				},
				["Quality"] = 2,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
			[49022] = {
				["Category"] = "消耗品",
				["DefaultScale"] = 0.6,
				["Desc"] = "打开获得4件战甲",
				["IconName"] = "普通子弹匣 ",
				["ModelId"] = 40000,
				["Name"] = "精致战甲匣",
				["NeedLevel"] = 1,
				["Param1"] = "reward",
				["Param2"] = "1015",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 1000,
				["Sort"] = "宝箱",
			},
		},
	},
	["Name2Atr"] = {
		["价格"] = "Price",
		["价钱类型"] = "PriceType",
		["使用类"] = "SubType",
		["使用绑定"] = "Binds",
		["出售价格"] = "SellPrice",
		["参数1"] = "Param1",
		["参数2"] = "Param2",
		["名称"] = "Name",
		["品质"] = "Quality",
		["图标名称"] = "IconName",
		["大类"] = "Category",
		["小类"] = "Sort",
		["小类Id"] = "SortId",
		["抽取结果"] = "Extraction",
		["描述"] = "Desc",
		["数量"] = "Amount",
		["有效期"] = "ExpiryDate",
		["模型ID"] = "ModelId",
		["每日使用上限"] = "MaxUseTimes",
		["绑定"] = "Bind",
		["缩放值"] = "DefaultScale",
		["自动使用"] = "AutoUse",
		["购买价格"] = "BuyPrice",
		["道具编号"] = "ItemId",
		["需求等级"] = "NeedLevel",
	},
	["RelationAttr"] = {
		["ItemId"] = {
			["AutoUse"] = true,
			["Bind"] = true,
			["BuyPrice"] = true,
			["Category"] = true,
			["DefaultScale"] = true,
			["Desc"] = true,
			["Extraction"] = true,
			["IconName"] = true,
			["MaxUseTimes"] = true,
			["ModelId"] = true,
			["Name"] = true,
			["NeedLevel"] = true,
			["Param1"] = true,
			["Param2"] = true,
			["Price"] = true,
			["PriceType"] = true,
			["Quality"] = true,
			["SellPrice"] = true,
			["Sort"] = true,
			["SortId"] = true,
			["SubType"] = true,
		},
	},
}