-- xls md5:679ea6d1d6f06a874d95ccf5105d1c35
return {
["字符_常量"] = {
		["A"] = {"string@ukey", "变量", "Item", "Money", "Gold", "Exp", "Soul", "Token", "Strength", "Sports", "YZMoney", "Exploit", "SkillPoint", "ZeroPower", "GiftEnergy", },
		["B"] = {"string", "类型", "int", "int", "int", "int", "int", "int", "int", "int", "int", "int", "int", "int", "int", },
		["C"] = {"string@default", "值", "1", "2", "3", "4", "5", "6", "12", 7, 8, 9, "10", 11, "13", },
		["D"] = {"string@default", "Key1", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", "REWARD_NAME2ID", },
		["E"] = {"string@default", "Key2", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", "REWARD_ID2NAME", },
	},
["flv参数"] = {
		["A"] = {"int@ukey", "等级", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, },
		["B"] = {"int", "值", 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255, 265, 275, 285, 295, 305, 315, 325, 335, 345, 355, 625, 645, 665, 685, 705, 725, 745, 765, 785, 805, 825, 845, 865, 885, 905, 925, 945, 965, 985, 1005, 1030, 1055, 1080, 1105, 1130, 1155, 1180, 1205, 1230, 1255, 1285, 1315, 1345, 1375, 1405, 1435, 1465, 1495, 1525, 1555, 1590, 1625, 1660, 1695, 1730, 1765, 1800, 1835, 1870, 1905, 1945, 1985, 2025, 2065, 2105, 2145, 2185, 2225, 2265, 2305, },
	},
["整型_常量"] = {
		["A"] = {"int", "变量", 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 1, 2, 3, 1, 2, },
		["B"] = {"string", "类型", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "number", "number", "number", "number", "number", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", },
		["C"] = {"string@default", "值", "CHAT_WORLD", "CHAT_ZONE", "CHAT_NOTICE", "CHAT_ACT", "CHAT_SYSTEM", "CHAT_GUILD", "世界", "地区", "公告", "活动", "系统", "公会", 5, 5, -1, -1, 5, "GoldLevel", "SkillLevel", "SkillValue", "ShenJiLevel", "ShenJiExp", "Status", "StarLv", "StarExp", "EnhanceLv", "EnhanceExp", "QualityValue", "BulletAUid", "BulletBUid", "Level", "BreakTime", "Exp", "CacheExp", "EngraveName", "EngraveText", "EngraveTime", "GoldStatus", "WashPoint", "女剑士", "男剑士", "女镰刀", "Add", "Del", },
		["D"] = {"string@default", "Key1", "CHANNEL_ID2NAME", "CHANNEL_ID2NAME", "CHANNEL_ID2NAME", "CHANNEL_ID2NAME", "CHANNEL_ID2NAME", "CHANNEL_ID2NAME", "CHANNEL_ID2SHOW_NAME", "CHANNEL_ID2SHOW_NAME", "CHANNEL_ID2SHOW_NAME", "CHANNEL_ID2SHOW_NAME", "CHANNEL_ID2SHOW_NAME", "CHANNEL_ID2SHOW_NAME", "CHANNEL_CD", "CHANNEL_CD", "CHANNEL_CD", "CHANNEL_CD", "CHANNEL_CD", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "ITEM_INFO_ID2NAME", "JOB_ID2NAME", "JOB_ID2NAME", "JOB_ID2NAME", "TOP_ID2NAME", "TOP_ID2NAME", },
		["E"] = {"string@default", "Key2", "NAME2CHANNEL_ID", "NAME2CHANNEL_ID", "NAME2CHANNEL_ID", "NAME2CHANNEL_ID", "NAME2CHANNEL_ID", "NAME2CHANNEL_ID", "SHOW_NAME2CHANNEL_ID", "SHOW_NAME2CHANNEL_ID", "SHOW_NAME2CHANNEL_ID", "SHOW_NAME2CHANNEL_ID", "SHOW_NAME2CHANNEL_ID", "SHOW_NAME2CHANNEL_ID", nil, nil, nil, nil, nil, "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "ITEM_INFO_NAME2ID", "JOB_NAME2ID", "JOB_NAME2ID", "JOB_NAME2ID", "TOP_NAME2ID", "TOP_NAME2ID", },
	},
["公式表"] = {
		["A"] = {"string@ukey", "公式名称", "攻击者命中率", "受击者闪避率", "命中率", "攻击者暴击率", "物理防御率公式", "法术抵抗率公式", "重力加速度", "跳跃重力加速度", "二段跳上升重力加速度", "空气阻力加速度", },
		["B"] = {"string@default", "参数列表", "Hit, F1", "Dodge, F2", "HitRate, DodgeRate", "Pram1,F", "Def, F", "Def, F", "SpeedY", "SpeedY", "SpeedY", "Speed", },
		["C"] = {"string", "公式实现", "(A*Hit/(C*F1)+1)", "(A*Dodge/(C*F2))", "HitRate - DodgeRate", "A*Pram1/(C*F)", "A*Def/(Def+C*F)", "A*Def/(Def+C*F)", "SpeedY = math.abs(SpeedY) local minG, maxG = 2.5, 4 local G = 0.01*SpeedY*SpeedY G = math.min(maxG, math.max(minG, G)) return G", "SpeedY = math.abs(SpeedY) local minG, maxG = 6, 8 local G = 0.01*SpeedY*SpeedY G = math.min(maxG, math.max(minG, G)) return G", "SpeedY = math.abs(SpeedY) local minG, maxG = 4, 8 local G = 0.01*SpeedY*SpeedY G = math.min(maxG, math.max(minG, G)) return G", "Speed = math.abs(Speed) local A = 0.5*0.01*Speed*Speed return 0", },
		["D"] = {"float@default", "A", 1, 1, nil, 1, 1, 1, nil, nil, nil, nil, },
		["E"] = {"float@default", "C", 2, 2, nil, 10, 3.66, 3.2, nil, nil, nil, nil, },
	},
["__SheetOrder"] = {
		["A"] = {"string", "常量表", "公式表", "flv参数", "全局常量", "通用_常量", "背包_常量", "字符_常量", "整型_常量", "交易行_常量", },
	},
["背包_常量"] = {
		["A"] = {"string@ukey", "变量", "GRID_PER_PAGE", "GRID_PER_LINE", "GRID_MAX_PAGE", "GRID_DEFAULT_OPEN", "GRID_OPEN_GOLD", "GRID_RAND", "GRID_TMP_MAX", "PAGE_EQUIP", "PAGE_EQUIP_GRIDMAX", "PAGE_NORMAL_GRIDMAX", "PAGE_NORMAL_START", "PAGE_NORMAL_TMP", "PAGE_MERCENARY_ONE", "PAGE_MERCENARY_TWO", "PAGE_MERCENARY_THREE", "PAGE_MERCENARY_GRIDMAX", "PAGE_FASHION", "PAGE_FASHION_GRIDMAX", "PAGE_TIDY_CD", "WEAPON_ORDER_TO_RABBET_1", "WEAPON_ORDER_TO_RABBET_2", "WEAPON_ORDER_TO_RABBET_3", "WEAPON_ORDER_TO_RABBET_4", "WEAPON_REFINE_PROTECT_ID", "WEAPON_VALUE_GRADE", "WEAPON_VALUE_GRADE_TO_CN", "WEAPON_TO_COLOR", "WEAPON_SKILL_NEED_ITEM_ID", "WEAPON_SKILL_VALUE_GRADE", "WEAPON_SKILL_VALUE_GRADE_TO_CN", "WEAPON_SKILL_RANDOM_DIVISOR", "WEAPON_TIAM_MING_RANDOM_VALUE", "WEAPON_RETURN_MATERIAL", "WEAPON_ATTRIBUTE_GRADE_VALUE", "WEAPON_WASH_VALUE", "WEAPON_GOLD_FORGE_NEED_ITEM_ID", "WEAPON_BASE_WASH_ITEM_GOLD", "WEAPON_HIGHT_WASH_ITEM_GOLD", "SHEN_JI_COMPOSITE_PERCNT", "SHEN_JI_COMPOSITE_NUM", "SHEN_JI_UPGRADE_PERCNT", "SHEN_JI_COMPOSITE_SUCCESS_REWARD", "SHEN_JI_COMPOSITE_FAIL_REWARD", "SHEN_JI_COMPOSITE_RANDOM", "SHEN_JI_RETURN_FEED_ITEM_IDS", "PAGE_PROPERTY_GRIDMAX", "PAGE_COMMON_CRIDMAX", "PAGE_CHIP_CRIDMAX", "PAGE_ORMAMENT_CRIDMAX", "GRID_COMMON_SAVEMAX", "GRID_PROPERTY_SAVEMAX", "GRID_CHIP_SAVEMAX", "GRID_ORMAMENT_SAVEMAX", "GRID_MERCENARY_ITEM_SAVEMAX", "EQUIP_UP_GRADE_STAR_NEED_ITEM_ID", "HIGH_EQUIP_UP_GRADE_STAR_NEED_ITEM_ID", "胸甲", "护腿", "腰带", "鞋子", "RELIC_RETURN_FEED_ITEM_IDS", "DEFEND_RETURN_FEED_ITEM_IDS", "EQUIP_INIT_CRIT_VALUE", "EQUIP_HIGH_OPEN_LEVEL", "EQUIP_RETURN_ENCHANCE_MONEY_FLV", "HIGH_EQUIP_RETURN_ENCHANCE_MONEY_FLV", "BASE_EQUIP_EXP_TO_FLV", "HIGH_EQUIP_EXP_TO_FLV", "ORNAMENT_REVERT", "ORNAMENT_ENGRAVE_ITEM", "ORNAMENT_WASH_RANDOM", "BULLET_LEVEL_MAX2", "BULLET_LEVEL_MAX3", "BULLET_LEVEL_MAX4", "BULLET_LEVEL_MAX5", "BULLET_RETURN_FEED_ITEM_IDS", "BULLET_REBIRTH_COST_YB", "BULLET_QUALITY_MONEY_FLV", },
		["B"] = {"string@default", "类型", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "table_number", "table_string", "table_string", "number", "table_number", "table_string", "table_number", "table_number", "table_number", "table_number", "table_type_level", "number", "number", "number", "number", "number", "number", "table_type_level", "table_type_level", "table_type_level", "table_number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "table_type_level", "table_type_level", "table_type_level", "table_type_level", "table_number", "table_number", "number", "number", "number", "number", "number", "number", "number", "table_item_list_ex", "table_type_level", "number", "number", "number", "number", "table_number", "table_type_level", "table_type_level", },
		["C"] = {"string", "值", 36, 6, 5, 4, 10, -1, 36, 1, 20, "2000", 11, 40, "32", "33", "34", "7", "35", "7", 5, "2", "4", "5", "6", "40049", "0,30,46,61", "#c666666较弱,#c7fbfff普通,#cffe433较强,#cff3333极强", "#cffffffff,#cff66bd00,#cff2ab6ff,#cffc55fff,#cffffde00", "40031", "0,0.2,0.4,0.6,0.8", "极低概率,低概率,一定概率,高概率,极高概率", "0.05,0.15,0.3,0.6,1.2", "8,12", "40000,10", "5,3,2,1", "50|60,75|25,95|13,100|2", "40032", "5", "2", "0.9", "3", "0.8", "2|10001,3|10003,4|10004", "2|10002,3|10001,4|10003", "2|50,3|20,4|5", "15004,15003,15002,15001", 150, 200, 150, 200, 10000, 10000, 10000, 1, 10000, "40033", "40033", "1|80,2|100", "2|85,3|105", "3|90,1|110", "1|95,2|115", "20304,20303,20302,20301", "20404,20403,20402,20401", 20, 40, 0.9, 0.9, 0.9, 0.9, 10, "0|45005|1", "10|80,20|70,30|60,40|50,50|50,60|40,70|40", 10, 20, 25, 30, "12024,12023,12022", "2|50,3|50,4|100,5|100,6|200", "2|1,3|1,4|1.2,5|1.4", },
		["D"] = {"string@default", "Key1", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "WEAPON_CONST", "SHEN_JI_CONST", "SHEN_JI_CONST", "SHEN_JI_CONST", "SHEN_JI_CONST", "SHEN_JI_CONST", "SHEN_JI_CONST", "SHEN_JI_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "ITEMBAG_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "EQUIP_CONST", "ORNAMENT_CONST", "ORNAMENT_CONST", "ORNAMENT_CONST", "BULLET_CONST", "BULLET_CONST", "BULLET_CONST", "BULLET_CONST", "BULLET_CONST", "BULLET_CONST", "BULLET_CONST", },
	},
["通用_常量"] = {
		["A"] = {"string@ukey", "变量", "SCENEUID", "X", "Y", "GSID", "UserCountLimit", "MaxLineNum", "Name", "Sex", "Job", "Level", "Exp", "CurExp", "LevelExp", "Money", "Gold", "RunSpeed", "Hp", "MaxHp", "Mp", "MaxMp", "Soul", "Sports", "YZMoney", "Exploit", "ZeroPower", "SkillPoint", "GiftEnergy", "Strength", "Fighting", "FaceIcon", "VipLevel", "IsVip", "FamilyName", "Expiry", "Token", "Fashion", "ArenaPoint", "ArmsPoint", "SevenActPoint", "UseMrecenaryId", "AddStrength", "MLevel", "NPC_ID", "PET_ID", "MONSTER_ID", "MERCENARY_ID", "TRIGGER_ID", "NameLenRange", "怪物死亡", "任务领取", "任务完成", "营救市民", "收集资源", "通关", "通关失败", "体力消耗", "对话", "强化", "突破", "穿戴", "获得物品", "更换子弹", "进阶", "佣兵上阵", "佣兵升级", "佣兵升阶", "佣兵升星", "子弹升级", "打造", "血技升级", "玩家升级", "VIP升级", "时装穿戴", "血技变更", "激活", "精炼", "升星", "属性洗练", "WAVE_START", "ADD_MONSTER", "ADD_NPC", "ADD_TRIGGER", "MONSTER_NOHP", "MONSTER_PART_DEAD", "MONSTER_ANGRY", "MONSTER_FAINT", "MONSTER_HP_CHANGE", "OBJ_HP_CHANGE", "TRIGGER_FINISH_STAGE", "TRIGGER_MONSTER_FAIL_STAGE", "ARENA_KILL_ENEMY", "玩家战斗力改变", "进入活动副本", "十连抽", "商店刷新", "功能开放", "强化大师", "充值", "角色改名", "DAY_CHANGE", "NEW_MERCENARY", "EXPEDITION_POINT_CHANGE", "MERCENARY_MISSION", "BORN", "STATE1", "STATE2", "左", "中", "右", "火", "冰", "雷", "风", "无", "无机械", "HERO_RING", "MONSTER_ARROW", "TODO_ARROW", "MONSTER_RANGE", "MONSTER_NUM", "SPEED", "DISTANCE", "BOSS_SPEED", "EXP_COE", "COMBO_INTERVAL", "ITEM_CLICK_INTERVAL", "ITEM_PICK_UP_DISTANCE", "ITEM_DROP_DISTANCE", "ITEM_DROP_DISTANCE_Y", "ITEM_PICK_UP_TIME", "ITEM_DROP_FLY_SPEED", "ITEM_DROP_DISAPPEAR", "ITEM_DROP_DELAY", "ITEM_REBIRTH_COST_GOLD", "USER1", "USER2", "NPC", "MONSTER", "MONSTER_F", "MONSTER_FF", "MONSTER_N", "MONSTER_NN", "MONSTER_NPC", "MONSTER_NPCC", "MONSTER_D", "MONSTER_DD", "MONSTER_W", "MONSTER_WW", "SHOP_MYSTERY_OPEN_VIP", "SHOP_MYSTERY_OPEN_STRENGTH", "SHOP_MYSTERY_OPEN_TIME", "STAGE_NORMAL_TYPE", "STAGE_ELITE_TYPE", "STAGE_DRAMA_TYPE", "STAGE_TRIAL_TYPE", "STAGE_MONSTERNEST_TYPE", "STAGE_BONUS_TYPE", "STAGE_EXPEDITION_TYPE", "STAGE_LUCKY_TYPE", "STAGE_ONHOOK_TYPE", "STAGE_ARENA_TYPE", "STAGE_TEAM_TYPE", "STAGE_SYNC_ARENA_TYPE", "LUCKY_STAGE_OPEN_PROBABILITY", "LUCKY_STAGE_PLAY_TIMES", "EXPEDITON_STAG_CHEST_MAX_TIMES", "STAR_TO_FLV", "EXPEDITON_FREE_TIMES", "MERCENARY_UP_LEVEL", "MERCENARY_FIGHT", "MERCENARY_UP_SKILL", "MERCENARY_UP_STAR", "MERCENARY_UP_RANK", "MERCENARY_ADD_SKILLPOINT", "MERCENARYGAME_MISSION_UPDATE", "TASK_INFO_UPDATE", "TASK_GIFT_UPDATE", "EQUIP_ENHANCE_SUCCESS", "MAIL_NEW_UPDATE", "MAIL_REWARD_UPDATE", "PLAYER_DETAIL", "AUTO_FIGHT_RABBET_LEVEL", "AUTO_FIGHT_LEVEL_RANGE", "MAIL_DAYS_TEXT", "MAIL_DAYS_REWARD", "TEAM_ENTER_TIME", "FORCE_ITEM_ID", "MERCENARY_AP_ON_HIT", "MERCENARY_AP_ON_ATTACK", "MERCENARY_AP_ON_SUBHP", "MERCENARY_AP_ON_MISSILE", "MERCENARY_AP_ON_RECOVER", "CHANGE_ROLE_NAME", "REPLENIS_SIGN_DAYS", "REPLENIS_SIGN_GOLD", },
		["B"] = {"string", "类型", "number", "number", "number", "number", "table_number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "table_number", "table_number", "table_number", "table_number", "table_number", "table_number", "string", "number", "number", "number", "number", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "table_number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "table_number", "number", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "table_string", "table_type_level", "table_type_level", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", },
		["C"] = {"string@default", "值", 1000, 7000, 6800, "1", "100,120,200,400,600,800,1000", 1000, 1, 2, 4, 5, 6, 7, 8, 9, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 30, 35, 37, 39, 40, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, "1000,9999", "100000,199999", "10000,29999", "30000,39999", "1000,9999", "2,6", "MONSTER_DIE", "2", "3", "4", "5", "STAGE_PASS", "STAGE_FAIL", "STRENGTH_SUB", "NPC_TALK", "ITEM_ENHANCE", "ITEM_BREAK", "EQUIP_WIELD", "ITEM_GET", "BULLET_CHANGE", "ITEM_ADVANCE", "MERCENARY_BATTLE", "MERCENARY_LEVELUP", "MERCENARY_RANKUP", "MERCENARY_STARUP", "BULLET_LEVELUP", "FORGE", "SKILL_LEVELUP", "玩家升级", "VIP_LEVELUP", "FASHION_WIELD", "SKILL_CHANGE", "ITEM_ACTIVE", "USER_REFINE", "ITEM_STARUP", "ITEM_WASHATTR", "WAVE_START", "ADD_MONSTER", "ADD_NPC", "ADD_TRIGGER", "MONSTER_NOHP", "MPART_DEAD", "MANGRY", "MFAINT", "MONSTER_HP_CHANGE", "OBJ_HP_CHANGE", "TRIGGER_FINISH_STAGE", "TRIGGER_MONSTER_FAIL_STAGE", "ARENA_KILL_ENEMY", "FIGHTING_CHANGE", "STAGE_ACTIVION", "LOTTEY_TEN", "SHOP_REFRESH", "FUNCTION_OPEN", "INTENSOFY", "RECHARGE", "CHANGE_ROLE_NAME", "DAY_CHANGE", "NEW_MERCENARY", "EXPEDITION_POINT_CHANGE", "MERCENARY_MISSION", "1", "2", "3", "1", "2", "3", "1", "2", "3", "4", "100", "101", "1016", "1014", "1015", "400,5000", "3", 280, 5000, 140, "10", "3", "0.3", 90, 50, 1, 3, 80, 3, 6, 50, "1", "2", "10", "20", 21, 22, 23, 24, 18, 16, 25, 26, 19, 17, "9", "120", "2", "1", "2", "3", 4, 5, "6", "7", "8", "9", "10", "11", "12", "50", "5", "6", "1,1.5,2.5", "1", "MERCENARY_UP_LEVEL", "MERCENARY_FIGHT", "MERCENARY_UP_SKILL", "MERCENARY_UP_STAR", "MERCENARY_UP_RANK", "MERCENARY_ADD_SKILLPOINT", "MERCENARYGAME_MISSION_UPDATE", "TASK_INFO_UPDATE", "TASK_GIFT_UPDATE", "EQUIP_ENHANCE_SUCCESS", "MAIL_NEW_UPDATE", "MAIL_REWARD_UPDATE", "MaxOp,MaxHp,Atk,MagAtk,Def,MagDef,DefRate,MagDefRate,Leech,Op,ReOp,MaxOp,Mastery,MasteryLv,CurativeEff,AllAtkAdd,AllDamageAdd,AllDamageReduce,MonsterDamage,Crit|CritRate,CritFactor,Hit|HitRate,WalkSpeedDelta,AtkSpeedDelta", "2|7,3|11,4|15", "1|7,8|19,20|29,30|70", "7", "30", 2, "40048", "1", "1", "1", 2, "1", 200, 5, 20, },
		["D"] = {"string@default", "Key1", "BORN_CONST", "BORN_CONST", "BORN_CONST", "BORN_CONST", "GSID_CONST", "GSID_CONST", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "ATT_NAME2ID", "RANGE_ID", "RANGE_ID", "RANGE_ID", "RANGE_ID", "RANGE_ID", nil, "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "EVENT_CONST", "TRIGGER_STATE", "TRIGGER_STATE", "TRIGGER_STATE", "ATK_DIR", "ATK_DIR", "ATK_DIR", "ATK_ELEMENT", "ATK_ELEMENT", "ATK_ELEMENT", "ATK_ELEMENT", "ATK_ELEMENT", "ATK_ELEMENT", "EFFECT_CONST", "EFFECT_CONST", "EFFECT_CONST", "EFFECT_CONST", "EFFECT_CONST", "BLOOD_CONST", "BLOOD_CONST", "BLOOD_CONST", "SKILL_CONST", "COMBAT_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "ITEM_CONST", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "CAMP", "SHOP_CONST", "SHOP_CONST", "SHOP_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "STAGE_CONST", "LUCKY_STAGE_CONST", "LUCKY_STAGE_CONST", "EXPEDITON_STAGE_CONST", "EXPEDITON_STAGE_CONST", "EXPEDITON_STAGE_CONST", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", "GLOBAL_EVENT", nil, "AUTO_FIGHT_CONST", "AUTO_FIGHT_CONST", "MAIL_CONST", "MAIL_CONST", "STAGE_CONST", "FORCE_CONST", "MERCENARY_CONST", "MERCENARY_CONST", "MERCENARY_CONST", "MERCENARY_CONST", "MERCENARY_CONST", "OTHER_CONST", "OTHER_CONST", "OTHER_CONST", },
		["E"] = {"string@default", "Key2", nil, nil, nil, nil, nil, nil, "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", "ATT_ID2NAME", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", "STAGE_ID2NAME", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
	},
["全局常量"] = {
		["A"] = {"string@ukey", "变量", "DEFAULT_ATK_DIR", "RUSH_EFFECT", "SHAKE_DIST", "SHAKE_TIMES", "SHAKE_FRAME", "CAMERA_CITY_DIST", "CAMERA_MELEE_DIST", "CAMERA_RANGE_DIST", "CAMERA_CITY_HEIGHT", "CAMERA_MELEE_HEIGHT", "CAMERA_RANGE_HEIGHT", "CAMERA_MELEE_MAX_HEIGHT", "CAMERA_RANGE_MAX_HEIGHT", "CAMERA_MIN_HEIGHT", "CAMERA_GHOST_DIST_PER", "CAMERA_GHOST_FOV", "CAMERA_DEFAULT_FOV", "GHOST_VIEW_ST", "RE_TIME_ST", "RE_TIME_HP", "RE_TIME_OP", "RE_TIME_SH", "RE_TIME_AP", "ZHAOSHI_CD", "BROKEN_DEF_RATE", "BROKEN_DEF_FRAME", "BROKEN_DEF_EFFECT", "BROKEN_DEF_DIST", "NATK_SPEED", },
		["B"] = {"string", "类型", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "table_number", "table_number", "number", "number", "table_number", },
		["C"] = {"string@default", "值", 2, 1012, 20, 2, 8, 650, "750", 250, 420, "650", 350, "1000", "1000", "100", 0.4, 90, 60, 1, 2, 5, 5, 5, 5, 7, "0.2,0.8", "2,6", 10084, "0.7", "1.5,1.5,1", },
	},
["交易行_常量"] = {
		["A"] = {"string@ukey", "变量", "ADPATERPRICE", "TRADEPOS", "TRADETAX", "TRADEENDURANCE", "TRADEBULLET", "TRADESKILL", "TRADEMATERIAL", "TRADEOTHER", "TRADEMAXPRICE", "TRADECLASS", "TRADECLASSNAME", "TRADEREFRESHCOST", },
		["B"] = {"string", "类型", "table_number", "number", "number", "number", "table_number", "table_number", "table_number", "table_number", "table_number", "table_string", "table_string", "number", },
		["C"] = {"string@default", "值", "-20,80", "8", "5", "86400", "40034,40035,40036,40037,40038,40039,40040", "48001,48015,48016,48023,48033,48002", "40043,40044,40045,40046,40033,40031,40032", "55001,55101,55201,55002,55102,55202", "-50,100", "TRADEBULLET,TRADESKILL,TRADEMATERIAL,TRADEOTHER", "子弹,血技,材料,其他", "20", },
		["D"] = {"string@default", "Key1", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", "TRADE_CONST", },
		["E"] = {"string@default", "Key2", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, },
	},
["常量表"] = {
		["A"] = {"string@ukey", "变量", "重力加速度", "地面摩擦加速度", "空气摩擦加速度", "主角跳跃初速度", "主角二跳初速度", "主角闪避初速度", "关卡资源", "背景音乐", "格挡减伤倍率", "弱点伤害加成初值", "暴伤初值", "体力", "技能跳跃速度", "荆棘发射距离", "荆棘发射速度", "荆棘飞行速度", "主场景加速倍率", "主场景加速时间", "主角锁怪距离", "格挡开始帧数", "完美格挡结束帧数", "自动战斗能量门槛", "一人吸血衰减系数", "二人吸血衰减系数", "三人吸血衰减系数", "四人吸血衰减系数", "五人吸血衰减系数", },
		["B"] = {"string", "类型", "number", "number", "number", "number", "number", "number", "string", "string", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", "number", },
		["C"] = {"string@default", "值", 15, 5, 1, 65, 50, 120, "desert_map001", nil, 30, 20, 50, 100, 100, 2000, 150, 200, 2, 2, 3000, 1, 4, 100, 100, 50, 30, 30, 30, },
	},
}