return 
{
	["Attribute"] = {
		["BaseAtr"] = {
			["Amount"] = {
				["CnName"] = "数量",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Binds"] = {
				["CnName"] = "使用绑定",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["ExpiryDate"] = {
				["CnName"] = "有效期",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["ItemId"] = {
				["CnName"] = "道具编号",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
		},
		["BuildAtr"] = {
			["AutoUse"] = {
				["CnName"] = "自动使用",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Bind"] = {
				["CnName"] = "绑定",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["BuyPrice"] = {
				["CnName"] = "购买价格",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Category"] = {
				["CnName"] = "大类",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["DefaultScale"] = {
				["CnName"] = "缩放值",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Desc"] = {
				["CnName"] = "描述",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Extraction"] = {
				["CnName"] = "抽取结果",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["IconName"] = {
				["CnName"] = "图标名称",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["MaxUseTimes"] = {
				["CnName"] = "每日使用上限",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["ModelId"] = {
				["CnName"] = "模型ID",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Name"] = {
				["CnName"] = "名称",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["NeedLevel"] = {
				["CnName"] = "需求等级",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Param1"] = {
				["CnName"] = "参数1",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Param2"] = {
				["CnName"] = "参数2",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Price"] = {
				["CnName"] = "价格",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["PriceType"] = {
				["CnName"] = "价钱类型",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Quality"] = {
				["CnName"] = "品质",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["SellPrice"] = {
				["CnName"] = "出售价格",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["Sort"] = {
				["CnName"] = "小类",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["SortId"] = {
				["CnName"] = "小类Id",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
			["SubType"] = {
				["CnName"] = "使用类",
				["KeyName"] = "ItemId",
				["PutClient"] = true,
				["SheetName"] = "配置表",
			},
		},
	},
	["ConstInfo"] = {
		["配置表"] = {
			[45001] = {
				["Binds"] = 1,
				["BuyPrice"] = 1000,
				["Category"] = "消耗品",
				["DefaultScale"] = 1,
				["Desc"] = "服用可恢复体力60点",
				["IconName"] = "物品_道具-1",
				["MaxUseTimes"] = 10,
				["Misc"] = {
				},
				["ModelId"] = 40007,
				["Name"] = "体力药剂",
				["NeedLevel"] = 1,
				["Param1"] = "Strength",
				["Param2"] = "60",
				["PriceType"] = {
					0,
				},
				["Quality"] = 3,
				["SellPrice"] = 10,
				["Sort"] = "恢复类药品",
				["SortId"] = 10001,
			},
		},
	},
	["Name2Atr"] = {
		["价格"] = "Price",
		["价钱类型"] = "PriceType",
		["使用类"] = "SubType",
		["使用绑定"] = "Binds",
		["出售价格"] = "SellPrice",
		["参数1"] = "Param1",
		["参数2"] = "Param2",
		["名称"] = "Name",
		["品质"] = "Quality",
		["图标名称"] = "IconName",
		["大类"] = "Category",
		["小类"] = "Sort",
		["小类Id"] = "SortId",
		["抽取结果"] = "Extraction",
		["描述"] = "Desc",
		["数量"] = "Amount",
		["有效期"] = "ExpiryDate",
		["模型ID"] = "ModelId",
		["每日使用上限"] = "MaxUseTimes",
		["绑定"] = "Bind",
		["缩放值"] = "DefaultScale",
		["自动使用"] = "AutoUse",
		["购买价格"] = "BuyPrice",
		["道具编号"] = "ItemId",
		["需求等级"] = "NeedLevel",
	},
	["RelationAttr"] = {
		["ItemId"] = {
			["AutoUse"] = true,
			["Bind"] = true,
			["BuyPrice"] = true,
			["Category"] = true,
			["DefaultScale"] = true,
			["Desc"] = true,
			["Extraction"] = true,
			["IconName"] = true,
			["MaxUseTimes"] = true,
			["ModelId"] = true,
			["Name"] = true,
			["NeedLevel"] = true,
			["Param1"] = true,
			["Param2"] = true,
			["Price"] = true,
			["PriceType"] = true,
			["Quality"] = true,
			["SellPrice"] = true,
			["Sort"] = true,
			["SortId"] = true,
			["SubType"] = true,
		},
	},
}